Repository cse110-fa22-group7/cse110-fa22-group7-project, pull requests merged in 2022-11, with the labels that each got.

#37 Followed suggestions made on previous pull request
  source/main.html
  source/posttemplate.html
Labels: frontend

#46 Add logo, make posts scrollable, create button css
  source/images/logo_1.svg
  source/images/logo_2.svg
  source/main.css
  source/main.html
Labels: frontend

#74 ADRS, Change checkbox to buttons, meeting notes
  admin/meetings/111622-sprint-3-review.md
  source/main.html
  specs/adrs/111622-Design.md
  specs/adrs/111622-Filter.md
  specs/adrs/111622-Popups.md
Labels: documentation

#80 Back end hongkun
  source/scripts/JournalPost.js
Labels: backend

#78 Makes filter section contain 2 dropdowns
  source/images/logo.svg
  source/images/logo_1.svg
  source/images/logo_2.svg
  source/main.css
  source/main.html
Labels: frontend

#83 upload meeting notes for 11/20
  admin/meetings/112022-Checkin.md
Labels: meeting-notes

#77 Filter Functionality
  .gitignore
  docs/JournalPost.html
  docs/JournalPost.js.html
  docs/global.html
  docs/index.html
  package-lock.json
  package.json
  source/main.html
  source/scripts/JournalPost.js
  source/tests/end2end.test.js
  source/tests/example_test.test.js
Labels: backend

#96 Updated site design
  source/main.css
  source/main.html
Labels: frontend

#108 Post to cards and header update
  source/main.css
  source/main.html
  source/posttemplate.html
  source/scripts/JournalPost.js
Labels: frontend
