Repository cse110-fa22-group7/cse110-fa22-group7-project, pull requests merged in 2022-12, with the labels that each got.

#121 upload 11/30/2022 meeting notes
  admin/meetings/112122-TaCheckin.md
  admin/meetings/113022-Finaltasks.md
  admin/meetings/113022-TaCheckin.md
Labels: meeting-notes

#127 Added Label Selector and Color Coded Posts
  source/images/logo.png
  source/main.css
  source/main.html
  source/posttemplate.html
  source/scripts/JournalPost.js
  source/scripts/main.js
Labels: frontend

#132 Button Css when clicked changes color
  source/main.css
  source/posttemplate.html
  source/scripts/JournalPost.js
Labels: frontend

#134 Update and bug fix for buttons
  source/createpopup.html
  source/main.css
  source/main.html
  source/scripts/JournalPost.js
  source/scripts/Popup.js
Labels: bug, frontend

#136 Add an introduction to README.md
  README.md
Labels: documentation

#138 Added e2e tests for edit and create cancels
  source/tests/end2end.test.js
Labels: Testing
